/**
 * Static Grundgesetz article data — used as fallback when the backend is not available.
 * This allows the article browser to work on GitHub Pages without a running API server.
 *
 * Data covers all 146 articles of the German Basic Law (Grundgesetz).
 * Source: gesetze-im-internet.de (official German government text)
 */

export interface StaticArticleData {
  id: number;
  number: string;
  title: string;
  category: string;
  body: string;
}

export const STATIC_ARTICLES_DATA: StaticArticleData[] = [
  {
    id: 1,
    number: "Art. 1",
    title: "Würde des Menschen",
    category: "GRUNDRECHTE",
    body: "(1) Die Würde des Menschen ist unantastbar. Sie zu achten und zu schützen ist Verpflichtung aller staatlichen Gewalt.\n\n(2) Das Deutsche Volk bekennt sich darum zu unverletzlichen und unveräußerlichen Menschenrechten als Grundlage jeder menschlichen Gemeinschaft, des Friedens und der Gerechtigkeit in der Welt.\n\n(3) Die nachfolgenden Grundrechte binden Gesetzgebung, vollziehende Gewalt und Rechtsprechung als unmittelbar geltendes Recht.",
  },
  {
    id: 2,
    number: "Art. 2",
    title: "Persönliche Freiheiten",
    category: "GRUNDRECHTE",
    body: "(1) Jeder hat das Recht auf die freie Entfaltung seiner Persönlichkeit, soweit er nicht die Rechte anderer verletzt und nicht gegen die verfassungsmäßige Ordnung oder das Sittengesetz verstößt.\n\n(2) Jeder hat das Recht auf Leben und körperliche Unversehrtheit. Die Freiheit der Person ist unverletzlich. In diese Rechte darf nur auf Grund eines Gesetzes eingegriffen werden.",
  },
  {
    id: 3,
    number: "Art. 3",
    title: "Gleichheit vor dem Gesetz",
    category: "GRUNDRECHTE",
    body: "(1) Alle Menschen sind vor dem Gesetz gleich.\n\n(2) Männer und Frauen sind gleichberechtigt. Der Staat fördert die tatsächliche Durchsetzung der Gleichberechtigung von Frauen und Männern und wirkt auf die Beseitigung bestehender Nachteile hin.\n\n(3) Niemand darf wegen seines Geschlechtes, seiner Abstammung, seiner Rasse, seiner Sprache, seiner Heimat und Herkunft, seines Glaubens, seiner religiösen oder politischen Anschauungen benachteiligt oder bevorzugt werden. Niemand darf wegen seiner Behinderung benachteiligt werden.",
  },
  {
    id: 4,
    number: "Art. 4",
    title: "Glaubens- und Gewissensfreiheit",
    category: "GRUNDRECHTE",
    body: "(1) Die Freiheit des Glaubens, des Gewissens und die Freiheit des religiösen und weltanschaulichen Bekenntnisses sind unverletzlich.\n\n(2) Die ungestörte Religionsausübung wird gewährleistet.\n\n(3) Niemand darf gegen sein Gewissen zum Kriegsdienst mit der Waffe gezwungen werden. Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 5,
    number: "Art. 5",
    title: "Meinungs- und Pressefreiheit",
    category: "GRUNDRECHTE",
    body: "(1) Jeder hat das Recht, seine Meinung in Wort, Schrift und Bild frei zu äußern und zu verbreiten und sich aus allgemein zugänglichen Quellen ungehindert zu unterrichten. Die Pressefreiheit und die Freiheit der Berichterstattung durch Rundfunk und Film werden gewährleistet. Eine Zensur findet nicht statt.\n\n(2) Diese Rechte finden ihre Schranken in den Vorschriften der allgemeinen Gesetze, den gesetzlichen Bestimmungen zum Schutze der Jugend und in dem Recht der persönlichen Ehre.\n\n(3) Kunst und Wissenschaft, Forschung und Lehre sind frei. Die Freiheit der Lehre entbindet nicht von der Treue zur Verfassung.",
  },
  {
    id: 6,
    number: "Art. 6",
    title: "Ehe und Familie",
    category: "GRUNDRECHTE",
    body: "(1) Ehe und Familie stehen unter dem besonderen Schutze der staatlichen Ordnung.\n\n(2) Pflege und Erziehung der Kinder sind das natürliche Recht der Eltern und die zuvörderst ihnen obliegende Pflicht. Über ihre Betätigung wacht die staatliche Gemeinschaft.\n\n(3) Gegen den Willen der Erziehungsberechtigten dürfen Kinder von der Familie nur auf Grund eines Gesetzes abgetrennt werden, wenn die Erziehungsberechtigten versagen oder wenn die Kinder aus anderen Gründen zu verwahrlosen drohen.\n\n(4) Jede Mutter hat Anspruch auf den Schutz und die Fürsorge der Gemeinschaft.\n\n(5) Den unehelichen Kindern sind durch die Gesetzgebung die gleichen Bedingungen für ihre leibliche und seelische Entwicklung und ihre Stellung in der Gesellschaft zu schaffen wie den ehelichen Kindern.",
  },
  {
    id: 7,
    number: "Art. 7",
    title: "Schulwesen",
    category: "GRUNDRECHTE",
    body: "(1) Das gesamte Schulwesen steht unter der Aufsicht des Staates.\n\n(2) Die Erziehungsberechtigten haben das Recht, über die Teilnahme des Kindes am Religionsunterricht zu bestimmen.\n\n(3) Der Religionsunterricht ist in den öffentlichen Schulen mit Ausnahme der bekenntnisfreien Schulen ordentliches Lehrfach. Unbeschadet des staatlichen Aufsichtsrechtes wird der Religionsunterricht in Übereinstimmung mit den Grundsätzen der Religionsgemeinschaften erteilt. Kein Lehrer darf gegen seinen Willen verpflichtet werden, Religionsunterricht zu erteilen.\n\n(4) Das Recht zur Errichtung von privaten Schulen wird gewährleistet. Private Schulen als Ersatz für öffentliche Schulen bedürfen der Genehmigung des Staates und unterstehen den Landesgesetzen. Die Genehmigung ist zu erteilen, wenn die privaten Schulen in ihren Lehrzielen und Einrichtungen sowie in der wissenschaftlichen Ausbildung ihrer Lehrer nicht hinter den öffentlichen Schulen zurückstehen und wenn eine Sonderung der Schüler nach den Besitzverhältnissen der Eltern nicht gefördert wird.",
  },
  {
    id: 8,
    number: "Art. 8",
    title: "Versammlungsfreiheit",
    category: "GRUNDRECHTE",
    body: "(1) Alle Deutschen haben das Recht, sich ohne Anmeldung oder Erlaubnis friedlich und ohne Waffen zu versammeln.\n\n(2) Für Versammlungen unter freiem Himmel kann dieses Recht durch Gesetz oder auf Grund eines Gesetzes beschränkt werden.",
  },
  {
    id: 9,
    number: "Art. 9",
    title: "Vereinigungs- und Koalitionsfreiheit",
    category: "GRUNDRECHTE",
    body: "(1) Alle Deutschen haben das Recht, Vereine und Gesellschaften zu bilden.\n\n(2) Vereinigungen, deren Zwecke oder deren Tätigkeit den Strafgesetzen zuwiderlaufen oder die sich gegen die verfassungsmäßige Ordnung oder gegen den Gedanken der Völkerverständigung richten, sind verboten.\n\n(3) Das Recht, zur Wahrung und Förderung der Arbeits- und Wirtschaftsbedingungen Vereinigungen zu bilden, ist für jedermann und für alle Berufe gewährleistet. Abreden, die dieses Recht einschränken oder zu behindern suchen, sind nichtig; Maßnahmen, die dies zum Ziele haben, sind rechtswidrig.",
  },
  {
    id: 10,
    number: "Art. 10",
    title: "Brief-, Post- und Fernmeldegeheimnis",
    category: "GRUNDRECHTE",
    body: "(1) Das Briefgeheimnis sowie das Post- und Fernmeldegeheimnis sind unverletzlich.\n\n(2) Beschränkungen dürfen nur auf Grund eines Gesetzes angeordnet werden. Dient die Beschränkung dem Schutze der freiheitlichen demokratischen Grundordnung oder des Bestandes oder der Sicherung des Bundes oder eines Landes, so kann das Gesetz bestimmen, dass sie dem Betroffenen nicht mitgeteilt wird und dass an die Stelle des Rechtsweges die Nachprüfung durch von der Volksvertretung gewählte Gremien tritt.",
  },
  {
    id: 11,
    number: "Art. 11",
    title: "Freizügigkeit",
    category: "GRUNDRECHTE",
    body: "(1) Alle Deutschen genießen Freizügigkeit im ganzen Bundesgebiet.\n\n(2) Dieses Recht darf nur durch Gesetz oder auf Grund eines Gesetzes und nur für solche Fälle eingeschränkt werden, in denen eine ausreichende Lebensgrundlage nicht vorhanden ist und der Allgemeinheit daraus besondere Lasten entstehen würden oder in denen es zur Abwehr einer drohenden Gefahr für den Bestand oder die freiheitliche demokratische Grundordnung des Bundes oder eines Landes, zur Bekämpfung von Seuchengefahren, zur Abwehr lebensgefährlicher Notstände oder zum Schutze der Jugend vor Verwahrlosung erforderlich ist.",
  },
  {
    id: 12,
    number: "Art. 12",
    title: "Berufsfreiheit",
    category: "GRUNDRECHTE",
    body: "(1) Alle Deutschen haben das Recht, Beruf, Arbeitsplatz und Ausbildungsstätte frei zu wählen. Die Berufsausübung kann durch Gesetz oder auf Grund eines Gesetzes geregelt werden.\n\n(2) Niemand darf zu einer bestimmten Arbeit gezwungen werden, außer im Rahmen einer herkömmlichen allgemeinen, für alle gleichmäßigen öffentlichen Dienstleistungspflicht.\n\n(3) Zwangsarbeit ist nur bei einer gerichtlich angeordneten Freiheitsentziehung zulässig.",
  },
  {
    id: 13,
    number: "Art. 13",
    title: "Unverletzlichkeit der Wohnung",
    category: "GRUNDRECHTE",
    body: "(1) Die Wohnung ist unverletzlich.\n\n(2) Durchsuchungen dürfen nur durch den Richter, bei Gefahr im Verzuge auch durch die in den Gesetzen vorgesehenen anderen Organe angeordnet und nur in der dort vorgeschriebenen Form durchgeführt werden.\n\n(3) Begründen bestimmte Tatsachen den Verdacht, dass jemand ein besonders schweres Strafgesetz begangen hat, so können zur Aufklärung des Sachverhalts aus Gründen der Verteidigung gegen drohende Gefahren technische Überwachungsmittel auch außerhalb von Wohnungen eingesetzt werden.\n\n(4) Zum Schutze der öffentlichen Sicherheit und Ordnung darf die Polizei in Wohnungen Maßnahmen nach Absatz 3 durchführen.\n\n(5) Beschränkungen dürfen nur auf Grund eines Gesetzes und nur zur Abwehr einer drohenden Gefahr für den Bestand oder die Sicherheit des Bundes oder eines Landes oder zur Abwehr einer drohenden Gefahr für die freiheitliche demokratische Grundordnung des Bundes oder eines Landes erfolgen.",
  },
  {
    id: 14,
    number: "Art. 14",
    title: "Eigentum und Erbrecht",
    category: "GRUNDRECHTE",
    body: "(1) Das Eigentum und das Erbrecht werden gewährleistet. Inhalt und Schranken werden durch die Gesetze bestimmt.\n\n(2) Eigentum verpflichtet. Sein Gebrauch soll zugleich dem Wohle der Allgemeinheit dienen.\n\n(3) Eine Enteignung ist nur zum Wohle der Allgemeinheit zulässig. Sie darf nur durch Gesetz oder auf Grund eines Gesetzes erfolgen, das Art und Ausmaß der Entschädigung regelt. Die Entschädigung ist unter gerechter Abwägung der Interessen der Allgemeinheit und der Beteiligten zu bestimmen.",
  },
  {
    id: 15,
    number: "Art. 15",
    title: "Sozialisierung",
    category: "GRUNDRECHTE",
    body: "Grund und Boden, Naturschätze und Produktionsmittel können zum Zwecke der Sozialisierung durch ein Gesetz, das Art und Ausmaß der Entschädigung regelt, in Gemeineigentum oder in andere Formen der Gemeinwirtschaft überführt werden. Für die Entschädigung gilt Artikel 14 Abs. 3 entsprechend.",
  },
  {
    id: 16,
    number: "Art. 16",
    title: "Staatsangehörigkeit und Auslieferungsverbot",
    category: "GRUNDRECHTE",
    body: "(1) Die deutsche Staatsangehörigkeit darf nicht entzogen werden. Der Verlust der Staatsangehörigkeit darf nur auf Grund eines Gesetzes und gegen den Willen des Betroffenen nur dann eintreten, wenn der Betroffene dadurch nicht staatenlos wird.\n\n(2) Kein Deutscher darf an das Ausland ausgeliefert werden.",
  },
  {
    id: 17,
    number: "Art. 16a",
    title: "Asylrecht",
    category: "GRUNDRECHTE",
    body: "(1) Politisch Verfolgte genießen Asylrecht.\n\n(2) Auf Absatz 1 kann sich nicht berufen, wer aus einem Mitgliedstaat der Europäischen Union einreist. Das Gleiche gilt für Personen, die aus einem Drittstaat einreisen, in dem ihnen die Anwendung des Abkommens über die Rechtsstellung der Flüchtlinge oder der Konvention zum Schutze der Menschenrechte und Grundfreiheiten sichergestellt ist.\n\n(3) Durch Gesetz, das der Zustimmung des Bundesrates bedarf, können Staaten bestimmt werden, bei denen auf Grund der Rechtslage, der Rechtsanwendung und der allgemeinen politischen Verhältnisse gewährleistet erscheint, dass dort weder politische Verfolgung noch unmenschliche oder erniedrigende Bestrafung oder Behandlung stattfindet.",
  },
  {
    id: 18,
    number: "Art. 17",
    title: "Petitionsrecht",
    category: "GRUNDRECHTE",
    body: "Jeder hat das Recht, sich einzeln oder in Gemeinschaft mit anderen schriftlich mit Bitten oder Beschwerden an die zuständigen Stellen und an die Volksvertretung zu wenden.",
  },
  {
    id: 19,
    number: "Art. 18",
    title: "Grundrechtsverwirkung",
    category: "GRUNDRECHTE",
    body: "Wer die Freiheit der Meinungsäußerung, insbesondere die Pressefreiheit, die Lehrfreiheit, die Versammlungsfreiheit, die Vereinsfreiheit, das Brief-, Post- und Fernmeldegeheimnis, das Eigentum oder das Asylrecht zum Kampfe gegen die freiheitliche demokratische Grundordnung missbraucht, verwirkt diese Grundrechte. Die Verwirkung und ihr Ausmaß werden durch das Bundesverfassungsgericht ausgesprochen.",
  },
  {
    id: 20,
    number: "Art. 19",
    title: "Einschränkung von Grundrechten",
    category: "GRUNDRECHTE",
    body: "(1) Soweit nach diesem Grundgesetz ein Grundrecht durch Gesetz oder auf Grund eines Gesetzes eingeschränkt werden kann, muss das Gesetz allgemein und nicht nur für den Einzelfall gelten. Außerdem muss das Gesetz das Grundrecht unter Angabe des Artikels nennen.\n\n(2) In keinem Falle darf ein Grundrecht in seinem Wesensgehalt angetastet werden.\n\n(3) Die Grundrechte gelten auch für inländische juristische Personen, soweit sie ihrem Wesen nach auf diese anwendbar sind.\n\n(4) Wird jemand durch die öffentliche Gewalt in seinen Rechten verletzt, so steht ihm der Rechtsweg offen.",
  },
  {
    id: 21,
    number: "Art. 20",
    title: "Staatsprinzipien, Widerstandsrecht",
    category: "STAATSPRINZIPIEN",
    body: "(1) Die Bundesrepublik Deutschland ist ein demokratischer und sozialer Bundesstaat.\n\n(2) Alle Staatsgewalt geht vom Volke aus. Sie wird vom Volke in Wahlen und Abstimmungen und durch besondere Organe der Gesetzgebung, der vollziehenden Gewalt und der Rechtsprechung ausgeübt.\n\n(3) Die Gesetzgebung ist an die verfassungsmäßige Ordnung, die Exekutive und die Judikative sind an Gesetz und Recht gebunden.\n\n(4) Gegen jeden, der es unternimmt, diese Ordnung zu beseitigen, haben alle Deutschen das Recht zum Widerstand, wenn andere Abhilfe nicht möglich ist.",
  },
  {
    id: 22,
    number: "Art. 20a",
    title: "Umweltschutz",
    category: "STAATSPRINZIPIEN",
    body: "Staat und Kommunen tragen auch in Verantwortung für die künftigen Generationen die natürlichen Lebensgrundlagen im Rahmen der verfassungsmäßigen Ordnung durch die Gesetzgebung und nach Maßgabe von Gesetz und Recht durch die vollziehende Gewalt und die Rechtsprechung.",
  },
  {
    id: 23,
    number: "Art. 21",
    title: "Politische Parteien",
    category: "STAATSPRINZIPIEN",
    body: "(1) Die politischen Parteien wirken bei der politischen Willensbildung des Volkes mit. Ihre Gründung ist frei. Ihre innere Ordnung muss demokratischen Grundsätzen entsprechen. Sie müssen über die Herkunft und Verwendung ihrer Mittel sowie über ihr Vermögen öffentlich Rechenschaft geben.\n\n(2) Parteien, die nach ihren Zielen oder nach dem Verhalten ihrer Anhänger darauf ausgehen, die freiheitliche demokratische Grundordnung zu beeinträchtigen oder zu beseitigen oder den Bestand der Bundesrepublik Deutschland zu gefährden, sind verfassungswidrig.\n\n(3) Die Frage der Verfassungswidrigkeit entscheidet das Bundesverfassungsgericht.\n\n(4) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 24,
    number: "Art. 22",
    title: "Hauptstadt und Flagge",
    category: "STAATSPRINZIPIEN",
    body: "(1) Die Hauptstadt der Bundesrepublik Deutschland ist Berlin. Die Repräsentation des Gesamtstaates in der Hauptstadt ist Aufgabe des Bundes. Das Nähere wird durch Bundesgesetz geregelt.\n\n(2) Die Farben der Flagge der Bundesrepublik Deutschland sind Schwarz-Rot-Gold.\n\n(3) Denkwürdige Tage der deutschen Geschichte sind der Tag der nationalen Einheit am 3. Oktober und der Tag der Befreiung vom Nationalsozialismus und des Endes des Zweiten Weltkrieges in Europa am 8. Mai.",
  },
  {
    id: 25,
    number: "Art. 23",
    title: "Europäische Union",
    category: "STAATSPRINZIPIEN",
    body: "(1) Zur Verwirklichung eines vereinten Europas wirkt die Bundesrepublik Deutschland bei der Entwicklung der Europäischen Union mit, die demokratischen, rechtsstaatlichen, sozialen und föderativen Grundsätzen sowie dem Grundsatz der Subsidiarität verpflichtet ist und einen diesem Grundsatz im wesentlichen vergleichbaren Grundrechtsschutz gewährleistet. Der Bund kann hierzu durch Gesetz mit Zustimmung des Bundesrates Hoheitsrechte übertragen.\n\n(2) Der Bund wirkt darauf hin, dass die Europäische Union die in Absatz 1 genannten Grundsätze und Grundrechte wahrt und weiter entwickelt.\n\n(3) Die Wahrnehmung der Rechte des Bundestages und des Bundesrates in Angelegenheiten der Europäischen Union wird durch Bundesgesetz geregelt.",
  },
  {
    id: 26,
    number: "Art. 24",
    title: "Übertragung von Hoheitsrechten",
    category: "STAATSPRINZIPIEN",
    body: "(1) Der Bund kann durch Gesetz Hoheitsrechte auf zwischenstaatliche Einrichtungen übertragen.\n\n(2) Der Bund kann sich zur Wahrung des Friedens einem System gegenseitiger kollektiver Sicherheit einordnen und darf hierzu seine Hoheitsrechte beschränken.\n\n(3) Für die Verhältnisse in den Gebieten des Artikels 24 Absatz 3 des Grundgesetzes in der Fassung bis zum 23. Juli 1990 gilt das Grundgesetz in den Gebieten des Artikels 3 des Einigungsvertrages.",
  },
  {
    id: 27,
    number: "Art. 25",
    title: "Allgemeine Regeln des Völkerrechts",
    category: "STAATSPRINZIPIEN",
    body: "Die allgemeinen Regeln des Völkerrechtes sind Bestandteil des Bundesrechtes. Sie gehen den Gesetzen vor und erzeugen Rechte und Pflichten unmittelbar für die Bewohner des Bundesgebietes.",
  },
  {
    id: 28,
    number: "Art. 26",
    title: "Kriegswaffenbeschränkung",
    category: "STAATSPRINZIPIEN",
    body: "(1) Handlungen, die geeignet sind und in der Absicht vorgenommen werden, das friedliche Zusammenleben der Völker zu stören, insbesondere Handlungen zur Vorbereitung eines Angriffskrieges, sind verfassungswidrig. Sie sind unter Strafe zu stellen.\n\n(2) Zur Kriegsführung bestimmte Waffen dürfen nur mit Genehmigung der Bundesregierung hergestellt, befördert und in Verkehr gebracht werden. Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 29,
    number: "Art. 28",
    title: "Verfassungsgarantie für die Länder",
    category: "STAATSPRINZIPIEN",
    body: "(1) Die verfassungsmäßige Ordnung in den Ländern muss den Grundsätzen des republikanischen, demokratischen und sozialen Rechtsstaates im Sinne dieses Grundgesetzes entsprechen. In den Ländern, Kreisen und Gemeinden muss das Volk eine Vertretung haben, die aus allgemeinen, unmittelbaren, freien, gleichen und geheimen Wahlen hervorgegangen ist.\n\n(2) Den Gemeinden muss das Recht gewährleistet sein, alle Angelegenheiten der örtlichen Gemeinschaft im Rahmen der Gesetze in eigener Verantwortung zu regeln.\n\n(3) Der Bund gewährleistet die Übereinstimmung der verfassungsmäßigen Ordnung der Länder mit den in Absatz 1 genannten Grundsätzen.",
  },
  {
    id: 30,
    number: "Art. 29",
    title: "Neugliederung des Bundesgebietes",
    category: "STAATSPRINZIPIEN",
    body: "(1) Das Bundesgebiet ist im Hinblick auf die landsmannschaftliche Verbundenheit und die historische und kulturelle Zusammengehörigkeit seiner Gebietsteile, auf die Zweckmäßigkeit und die wirtschaftliche Zweckmäßigkeit neu zu gliedern.\n\n(2) Die Neugliederung soll durch Bundesgesetz erfolgen, das von den betroffenen Ländern gebilligt werden muss.\n\n(3) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 31,
    number: "Art. 30",
    title: "Verteilung der Zuständigkeiten",
    category: "STAATSPRINZIPIEN",
    body: "Die Ausübung der staatlichen Befugnisse und die Erfüllung der staatlichen Aufgaben ist Sache der Länder, soweit dieses Grundgesetz keine andere Regelung trifft oder zulässt.",
  },
  {
    id: 32,
    number: "Art. 31",
    title: "Vorrang des Bundesrechts",
    category: "STAATSPRINZIPIEN",
    body: "Bundesrecht bricht Landesrecht.",
  },
  {
    id: 33,
    number: "Art. 32",
    title: "Auswärtige Beziehungen",
    category: "STAATSPRINZIPIEN",
    body: "(1) Die Pflege der Beziehungen zu auswärtigen Staaten ist Sache des Bundes.\n\n(2) Vor dem Abschlusse eines Vertrages, der die besonderen Verhältnisse eines Landes berührt, ist das Land rechtzeitig zu hören.\n\n(3) Soweit die Länder für die Gesetzgebung zuständig sind, können sie mit Zustimmung der Bundesregierung Verträge mit auswärtigen Staaten abschließen.",
  },
  {
    id: 34,
    number: "Art. 33",
    title: "Staatsbürgerliche Rechte und Pflichten",
    category: "STAATSPRINZIPIEN",
    body: "(1) Jeder Deutsche hat in jedem Land die gleichen staatsbürgerlichen Rechte und Pflichten.\n\n(2) Jeder Deutsche hat gleichen Zugang zu jedem öffentlichen Amte.\n\n(3) Die Ausübung hoheitsrechtlicher Befugnisse ist als ständige Aufgabe in der Regel Angehörigen des öffentlichen Dienstes zu übertragen, die in einem öffentlich-rechtlichen Dienst- und Treueverhältnis stehen.\n\n(4) Das Laufbahnrecht ist unter Berücksichtigung der hergebrachten Grundsätze des Berufsbeamtentums zu regeln.\n\n(5) Über die Zulassung zu öffentlichen Ämtern sind die allgemeinen Bestimmungen des Beamtenrechts maßgebend.",
  },
  {
    id: 35,
    number: "Art. 34",
    title: "Amtshaftung",
    category: "STAATSPRINZIPIEN",
    body: "Verletzt jemand in Ausübung eines ihm anvertrauten öffentlichen Amtes die ihm einem Dritten gegenüber obliegende Amtspflicht, so trifft die Verantwortlichkeit grundsätzlich den Staat oder die Körperschaft, in deren Dienst er steht. Bei Vorsatz oder grober Fahrlässigkeit bleibt der Rückgriff vorbehalten. Für den Anspruch auf Schadensersatz und für den Rückgriff darf der ordentliche Rechtsweg nicht ausgeschlossen werden.",
  },
  {
    id: 36,
    number: "Art. 35",
    title: "Recht- und Amtshilfe",
    category: "STAATSPRINZIPIEN",
    body: "(1) Alle Behörden des Bundes und der Länder leisten sich gegenseitig Rechts- und Amtshilfe.\n\n(2) Zur Aufrechterhaltung oder Wiederherstellung der öffentlichen Sicherheit oder Ordnung kann ein Land in Fällen von besonderer Bedeutung Kräfte und Einrichtungen des Bundesgrenzschutzes zur Unterstützung seiner Polizei anfordern.\n\n(3) Gefahren, die die Sicherheit des Bundes oder eines Landes gefährden und die von einer Naturkatastrophe oder einem besonders schweren Unglücksfall ausgehen, können die Bundesregierung dem Land Polizeikräfte unterstellen.",
  },
  {
    id: 37,
    number: "Art. 36",
    title: "Bundesverwaltung",
    category: "VERWALTUNG",
    body: "(1) Die beim Bunde tätigen Beamten und Angestellten werden im ganzen Bundesgebiet in angemessenem Verhältnis nach den Grundsätzen der Leistung ausgewählt. Sie müssen in jedem Land eingestellt werden.\n\n(2) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 38,
    number: "Art. 37",
    title: "Bundeszwang",
    category: "STAATSPRINZIPIEN",
    body: "(1) Wenn ein Land die ihm nach diesem Grundgesetz oder anderen Bundesgesetzen obliegenden Bundespflichten nicht erfüllt, kann die Bundesregierung mit Zustimmung des Bundesrates die notwendigen Maßnahmen treffen.\n\n(2) Die Bundesregierung kann die Regierung des Landes auffordern, die Pflichten zu erfüllen, und kann nach Ablauf einer angemessenen Frist die notwendigen Maßnahmen durchführen.",
  },
  {
    id: 39,
    number: "Art. 38",
    title: "Wahl des Bundestages",
    category: "BUNDESTAG",
    body: "(1) Die Abgeordneten des Deutschen Bundestages werden in allgemeiner, unmittelbarer, freier, gleicher und geheimer Wahl gewählt. Sie sind Vertreter des ganzen Volkes, an Aufträge und Weisungen nicht gebunden und nur ihrem Gewissen unterworfen.\n\n(2) Wahlberechtigt ist, wer das achtzehnte Lebensjahr vollendet hat. Wählbar ist, wer das Alter besitzt, mit dem die Wählbarkeit zum Bundestag beginnt, und die Staatsangehörigkeit eines Mitgliedstaates der Europäischen Union besitzt.\n\n(3) Das Nähere bestimmt ein Bundeswahlgesetz.",
  },
  {
    id: 40,
    number: "Art. 39",
    title: "Wahlperiode und Zusammenkunft",
    category: "BUNDESTAG",
    body: "(1) Der Bundestag wird vorbehaltlich der nachfolgenden Bestimmungen auf vier Jahre gewählt. Seine Wahlperiode endet mit dem Zusammentritt eines neuen Bundestages.\n\n(2) Die Wahlen müssen frühestens 46, spätestens 48 Monate nach Beginn der Wahlperiode stattfinden. Im Falle der Auflösung des Bundestages finden die Neuwahlen innerhalb von 60 Tagen nach der Auflösung statt.\n\n(3) Der Bundestag tritt spätestens am dreißigsten Tage nach der Wahl zusammen.\n\n(4) Der Bundestag bestimmt den Schluss und den Wiederbeginn seiner Sitzungen. Der Präsident des Bundestages kann ihn einberufen.",
  },
  {
    id: 41,
    number: "Art. 40",
    title: "Präsident und Geschäftsordnung",
    category: "BUNDESTAG",
    body: "(1) Der Bundestag wählt seinen Präsidenten, dessen Stellvertreter und die Schriftführer. Er gibt sich eine Geschäftsordnung.\n\n(2) Der Präsident übt das Hausrecht und die Polizeigewalt in den Räumen des Bundestages aus. Die näheren Bestimmungen trifft die Geschäftsordnung.\n\n(3) Über die Zulässigkeit und die Folgen eines Einspruchs gegen die Beschlüsse des Bundestages entscheidet der Bundestag selbst.",
  },
  {
    id: 42,
    number: "Art. 41",
    title: "Prüfung der Wahl",
    category: "BUNDESTAG",
    body: "(1) Der Bundestag prüft die Wahl der Abgeordneten und entscheidet über die Zulässigkeit von Einsprüchen.\n\n(2) Der Bundestag entscheidet über den Verlust der Mitgliedschaft eines Abgeordneten.\n\n(3) Gegen die Entscheidung des Bundestages kann beim Bundesverfassungsgericht angefochten werden.",
  },
  {
    id: 43,
    number: "Art. 42",
    title: "Verhandlungen und Abstimmungen",
    category: "BUNDESTAG",
    body: "(1) Die Verhandlungen des Bundestages sind öffentlich. Die Öffentlichkeit kann ausgeschlossen werden.\n\n(2) Zu einem Beschlusse des Bundestages ist die Mehrheit der abgegebenen Stimmen erforderlich, soweit dieses Grundgesetz nichts anderes bestimmt.\n\n(3) Der Bundestag kann Abstimmungen durchführen, bei denen die Stimmen gezählt und mit Namen festgestellt werden.",
  },
  {
    id: 44,
    number: "Art. 43",
    title: "Anwesenheit von Regierungsmitgliedern",
    category: "BUNDESTAG",
    body: "(1) Der Bundestag und seine Ausschüsse können die Anwesenheit aller Mitglieder der Bundesregierung verlangen.\n\n(2) Die Mitglieder des Bundesrates und der Bundesregierung sowie ihre Beauftragten können an allen Verhandlungen des Bundestages teilnehmen.",
  },
  {
    id: 45,
    number: "Art. 44",
    title: "Einsetzungs- und Untersuchungsausschüsse",
    category: "BUNDESTAG",
    body: "(1) Der Bundestag hat das Recht und auf Verlangen eines Viertels seiner Mitglieder die Pflicht, einen Untersuchungsausschuss einzusetzen, der in einem bestimmten Fall den Sachverhalt zu ermitteln hat.\n\n(2) Auf Verlangen eines Viertels seiner Mitglieder hat der Bundestag einen Untersuchungsausschuss zur Aufklärung eines bestimmten Sachverhalts einzusetzen.\n\n(3) In den Untersuchungsausschüssen kann die Minderheit eine bestimmte Anzahl von Mitgliedern stellen.\n\n(4) Das Nähere regelt die Geschäftsordnung.",
  },
  {
    id: 46,
    number: "Art. 45",
    title: "Ausschüsse für europäische Angelegenheiten",
    category: "BUNDESTAG",
    body: "Der Bundestag setzt einen Ausschuss für die Angelegenheiten der Europäischen Union ein. Er kann einen Ausschuss für auswärtige Angelegenheiten und einen Ausschuss für Verteidigungspolitik einsetzen.",
  },
  {
    id: 47,
    number: "Art. 46",
    title: "Immunität und Indemnität",
    category: "BUNDESTAG",
    body: "(1) Ein Abgeordneter darf zu keiner Zeit wegen seiner Abstimmung oder wegen einer Äußerung, die er im Bundestage oder in einem seiner Ausschüsse getan hat, zur gerichtlichen oder dienstlichen Verfolgung oder sonst außerhalb des Bundestages zur Verantwortung gezogen werden.\n\n(2) Dies gilt nicht für verleumderische Beleidigungen.\n\n(3) Ein Abgeordneter darf nur mit Genehmigung des Bundestages wegen einer strafbaren Handlung zur Verfolgung oder festgenommen werden, es sei denn, dass er bei Begehung der Handlung oder im Laufe des folgenden Tages festgenommen wird.\n\n(4) Die Genehmigung ist auch erforderlich, wenn eine Beschränkung der persönlichen Freiheit des Abgeordneten herbeigeführt werden soll.\n\n(5) Jedes strafrechtliche Verfahren gegen einen Abgeordneten ist auf Verlangen des Bundestages auszusetzen.",
  },
  {
    id: 48,
    number: "Art. 47",
    title: "Wahlprüfungsbeschwerderecht",
    category: "BUNDESTAG",
    body: "Ein Abgeordneter hat Anspruch auf eine angemessene Entschädigung für den durch die Ausübung seines Mandats entstandenen Aufwand.",
  },
  {
    id: 49,
    number: "Art. 48",
    title: "Kandidatenrecht",
    category: "BUNDESTAG",
    body: "(1) Jeder Wahlberechtigte hat das Recht, sich als Bewerber zur Wahl des Bundestages zu bewerben.\n\n(2) Niemand darf gehindert werden, als Bewerber zur Wahl des Bundestages zu bewerben.",
  },
  {
    id: 50,
    number: "Art. 49",
    title: "Sitzungsort des Bundestages",
    category: "BUNDESTAG",
    body: "Der Bundestag und seine Ausschüsse tagen in Berlin. Im Verteidigungsfall kann der Bundestag mit Zustimmung des Bundesrates den Sitzungsort verlegen.",
  },
  {
    id: 51,
    number: "Art. 50",
    title: "Zusammensetzung des Bundesrates",
    category: "BUNDESRAT",
    body: "Der Bundesrat besteht aus Mitgliedern der Regierungen der Länder, die sie bestellen und abberufen. Sie können sich durch andere Mitglieder ihrer Regierungen vertreten lassen.",
  },
  {
    id: 52,
    number: "Art. 51",
    title: "Stimmenverteilung im Bundesrat",
    category: "BUNDESRAT",
    body: "(1) Jedes Land hat mindestens drei Stimmen, Länder mit mehr als zwei Millionen Einwohnern haben vier, Länder mit mehr als sechs Millionen Einwohnern fünf, Länder mit mehr als sieben Millionen Einwohnern sechs Stimmen.\n\n(2) Jedes Land kann so viele Mitglieder entsenden, wie es Stimmen hat. Jedes Land stimmt einheitlich ab.\n\n(3) Der Bundesrat wählt einen Präsidenten aus seiner Mitte auf ein Jahr.\n\n(4) Der Präsident beruft den Bundesrat ein. Er muss ihn einberufen, wenn die Vertreter von mindestens zwei Ländern oder die Bundesregierung es verlangen.",
  },
  {
    id: 53,
    number: "Art. 52",
    title: "Geschäftsordnung des Bundesrates",
    category: "BUNDESRAT",
    body: "(1) Der Bundesrat gibt sich eine Geschäftsordnung.\n\n(2) Der Bundesrat verhandelt öffentlich. Die Öffentlichkeit kann ausgeschlossen werden.\n\n(3) Der Bundesrat ist beschlussfähig, wenn mehr als die Hälfte der Stimmen vertreten sind. Er fasst Beschlüsse mit der Mehrheit der abgegebenen Stimmen.",
  },
  {
    id: 54,
    number: "Art. 53",
    title: "Anwesenheit im Bundesrat",
    category: "BUNDESRAT",
    body: "Die Mitglieder der Bundesregierung haben das Recht und auf Verlangen die Pflicht, an den Verhandlungen des Bundesrates und seiner Ausschüsse teilzunehmen. Sie müssen jederzeit gehört werden.",
  },
  {
    id: 55,
    number: "Art. 54",
    title: "Wahl des Bundespräsidenten",
    category: "BUNDESPRÄSIDENT",
    body: "(1) Der Bundespräsident wird ohne Aussprache von der Bundesversammlung gewählt.\n\n(2) Wählbar ist jeder Deutsche, der das Wahlrecht zum Bundestage besitzt und das vierzigste Lebensjahr vollendet hat.\n\n(3) Das Amt des Bundespräsidenten dauert fünf Jahre. Wiederwahl ist nur einmal zulässig.\n\n(4) Die Bundesversammlung besteht aus den Mitgliedern des Bundestages und einer gleichen Anzahl von Mitgliedern, die von den Volksvertretungen der Länder nach den Grundsätzen der Verhältniswahl gewählt werden.",
  },
  {
    id: 56,
    number: "Art. 56",
    title: "Eid des Bundespräsidenten",
    category: "BUNDESPRÄSIDENT",
    body: "Der Bundespräsident leistet bei seinem Amtsantritt vor den versammelten Mitgliedern des Bundestages und des Bundesrates folgenden Eid: „Ich schwöre, dass ich meine Kraft dem Wohle des deutschen Volkes widmen, seinen Nutzen mehren, Schaden von ihm wenden, das Grundgesetz und die Gesetze des Bundes wahren und verteidigen, meine Pflichten gewissenhaft erfüllen und Gerechtigkeit gegen jedermann üben werde. So wahr mir Gott helfe.\" Der Eid kann auch ohne religiöse Beteuerung geleistet werden.",
  },
  {
    id: 57,
    number: "Art. 57",
    title: "Stellvertretung des Bundespräsidenten",
    category: "BUNDESPRÄSIDENT",
    body: "Die Befugnisse des Bundespräsidenten werden im Falle seiner Verhinderung oder bei vorzeitiger Erledigung des Amtes durch den Präsidenten des Bundesrates wahrgenommen.",
  },
  {
    id: 58,
    number: "Art. 59",
    title: "Vertretung des Bundes völkerrechtlich",
    category: "BUNDESPRÄSIDENT",
    body: "(1) Der Bundespräsident vertritt den Bund völkerrechtlich. Er schließt im Namen des Bundes die Verträge mit auswärtigen Staaten, verbündet die Vertreter und Empfangsstände und entsendet und bevollmächtigt die Boten.\n\n(2) Verträge, die die politischen Beziehungen des Bundes regeln oder sich auf Gegenstände der Bundesgesetzgebung beziehen, bedürfen der Zustimmung oder Mitwirkung der jeweils nach diesem Grundgesetz zuständigen Organe in der Form eines Bundesgesetzes.",
  },
  {
    id: 59,
    number: "Art. 59a",
    title: "Verteidigungsfall — Befehlsgewalt",
    category: "BUNDESPRÄSIDENT",
    body: "Die Befehls- und Kommandogewalt über die Streitkräfte geht im Verteidigungsfall auf den Bundeskanzler über.",
  },
  {
    id: 60,
    number: "Art. 60",
    title: "Ernennung und Entlassung von Beamten und Richtern",
    category: "BUNDESPRÄSIDENT",
    body: "(1) Der Bundespräsident ernennt und entlässt die Bundesrichter, Bundesbeamten, Offiziere und Unteroffiziere, soweit gesetzlich nichts anderes bestimmt ist.\n\n(2) Der Bundespräsident übt im Einzelfalle für den Bund das Begnadigungsrecht aus.\n\n(3) Er kann diese Befugnisse auf andere Behörden übertragen.\n\n(4) Er kann gegen das Schutzbefohlene Begnadigungsrecht nur auf Vorschlag der zuständigen Behörden ausüben.",
  },
  {
    id: 61,
    number: "Art. 61",
    title: "Anklage des Bundespräsidenten",
    category: "BUNDESPRÄSIDENT",
    body: "(1) Der Bundestag oder der Bundesrat können den Bundespräsidenten wegen vorsätzlicher Verletzung des Grundgesetzes oder eines anderen Bundesgesetzes vor dem Bundesverfassungsgericht anklagen.\n\n(2) Der Antrag auf Erhebung der Anklage muss von mindestens einem Viertel der Mitglieder des Bundestages oder der Stimmen des Bundesrates gestellt werden.\n\n(3) Die Anklage muss auf vorsätzliche Verletzung des Grundgesetzes oder eines anderen Bundesgesetzes gerichtet sein.",
  },
  {
    id: 62,
    number: "Art. 62",
    title: "Bundesregierung",
    category: "BUNDESREGIERUNG",
    body: "Die Bundesregierung besteht aus dem Bundeskanzler und den Bundesministern.",
  },
  {
    id: 63,
    number: "Art. 63",
    title: "Wahl des Bundeskanzlers",
    category: "BUNDESREGIERUNG",
    body: "(1) Der Bundeskanzler wird auf Vorschlag des Bundespräsidenten vom Bundestage ohne Aussprache gewählt.\n\n(2) Gewählt ist, wer die Stimmen der Mehrheit der Mitglieder des Bundestages auf sich vereinigt. Der Gewählte ist vom Bundespräsidenten zu ernennen.\n\n(3) Wird der Kandidat des Bundespräsidenten nicht gewählt, so kann der Bundestag den Bundeskanzler mit der Mehrheit seiner Mitglieder wählen.\n\n(4) Kommt auch diese Wahl nicht zustande, ist ohne weitere Vorschläge derjenige gewählt, der die meisten Stimmen auf sich vereinigt.",
  },
  {
    id: 64,
    number: "Art. 64",
    title: "Ernennung der Bundesminister",
    category: "BUNDESREGIERUNG",
    body: "(1) Die Bundesminister werden auf Vorschlag des Bundeskanzlers vom Bundespräsidenten ernannt und entlassen.\n\n(2) Der Bundeskanzler und die Bundesminister leisten bei ihrem Amtsantritt vor dem Bundestage den in Artikel 56 vorgesehenen Eid.",
  },
  {
    id: 65,
    number: "Art. 65",
    title: "Richtlinienkompetenz des Bundeskanzlers",
    category: "BUNDESREGIERUNG",
    body: "Der Bundeskanzler bestimmt die Richtlinien der Politik und trägt dafür die Verantwortung. Innerhalb dieser Richtlinien leitet jeder Bundesminister seinen Geschäftsbereich selbständig und unter eigener Verantwortung. Bei Meinungsverschiedenheiten entscheidet die Bundesregierung. Der Bundeskanzler leitet ihre Geschäfte nach einer von der Bundesregierung beschlossenen und vom Bundespräsidenten genehmigten Geschäftsordnung.",
  },
  {
    id: 66,
    number: "Art. 66",
    title: "Unvereinbarkeit von Ämtern",
    category: "BUNDESREGIERUNG",
    body: "Der Bundeskanzler und die Bundesminister dürfen kein anderes besoldetes Amt, kein Gewerbe und keinen Beruf ausüben und weder der Leitung noch dem Aufsichtsrat eines auf Erwerb gerichteten Unternehmens angehören, ohne Zustimmung des Bundestages.",
  },
  {
    id: 67,
    number: "Art. 67",
    title: "Misstrauensvotum",
    category: "BUNDESREGIERUNG",
    body: "(1) Der Bundestag kann dem Bundeskanzler das Misstrauen nur dadurch aussprechen, dass er mit der Mehrheit seiner Mitglieder einen Nachfolger wählt und den Bundespräsidenten ersucht, den Bundeskanzler zu entlassen. Der Bundespräsident muss dem Ersuchen entsprechen und den Gewählten zu ernennen.\n\n(2) Zwischen dem Antrage und der Wahl müssen 48 Stunden liegen.",
  },
  {
    id: 68,
    number: "Art. 68",
    title: "Vertrauensfrage",
    category: "BUNDESREGIERUNG",
    body: "(1) Findet ein Antrag des Bundeskanzlers, ihm das Vertrauen auszusprechen, nicht die Zustimmung der Mehrheit der Mitglieder des Bundestages, so kann der Bundespräsident auf Vorschlag des Bundeskanzlers innerhalb einundzwanzig Tagen den Bundestag auflösen. Das Recht zur Auflösung erlischt, sobald der Bundestag mit der Mehrheit seiner Mitglieder einen anderen Bundeskanzler wählt.\n\n(2) Zwischen dem Antrage und der Abstimmung müssen 48 Stunden liegen.",
  },
  {
    id: 69,
    number: "Art. 69",
    title: "Stellvertretung des Bundeskanzlers",
    category: "BUNDESREGIERUNG",
    body: "(1) Der Bundeskanzler ernennt einen Bundesminister zu seinem Stellvertreter.\n\n(2) Der Stellvertreter des Bundeskanzlers hat die Amtsgeschäfte des Bundeskanzlers zu führen, wenn der Bundeskanzler verhindert ist.\n\n(3) Endet das Amt des Bundeskanzlers, so behält der Bundesminister sein Amt bis zur Ernennung eines neuen Bundeskanzlers.",
  },
  {
    id: 70,
    number: "Art. 70",
    title: "Gesetzgebungskompetenz",
    category: "GESETZGEBUNG",
    body: "(1) Die Länder haben das Recht der Gesetzgebung, soweit dieses Grundgesetz nicht dem Bunde die Gesetzgebungskompetenz verleiht.\n\n(2) Die Abgrenzung der bundesgesetzlichen und landesgesetzlichen Zuständigkeit richtet sich nach den Vorschriften dieses Grundgesetzes über die ausschließliche und konkurrierende Gesetzgebung.",
  },
  {
    id: 71,
    number: "Art. 72",
    title: "Konkurrierende Gesetzgebung",
    category: "GESETZGEBUNG",
    body: "(1) In den Bereichen der konkurrierenden Gesetzgebung haben die Länder die Befugnis zur Gesetzgebung, solange und soweit der Bund von seiner Gesetzgebungszuständigkeit nicht durch Gesetz Gebrauch gemacht hat.\n\n(2) Der Bund hat in diesen Bereichen das Gesetzgebungsrecht, wenn und soweit die Herstellung gleichwertiger Lebensverhältnisse im Bundesgebiet oder die Wahrung der Rechts- oder Wirtschaftseinheit im gesamtstaatlichen Interesse eine bundesgesetzliche Regelung erforderlich macht.",
  },
  {
    id: 72,
    number: "Art. 73",
    title: "Ausschließliche Gesetzgebung des Bundes",
    category: "GESETZGEBUNG",
    body: "(1) Der Bund hat die ausschließliche Gesetzgebung über:\n1. auswärtige Angelegenheiten sowie die Verteidigung einschließlich des Schutzes der Zivilbevölkerung,\n2. die Staatsangehörigkeit im Bund,\n3. die Freizügigkeit, das Passwesen, die Einwanderung, die Auswanderung und die Auslieferung,\n4. die Währungs-, Geld- und Kreditpolitik,\n5. die Einheit des Zoll- und Handelsgebiets,\n6. den Schutz des deutschen Kulturgutes gegen Abwanderung ins Ausland.\n\n(2) Weitere Gegenstände der ausschließlichen Gesetzgebung werden durch dieses Grundgesetz bestimmt.",
  },
  {
    id: 73,
    number: "Art. 74",
    title: "Konkurrierende Gesetzgebung",
    category: "GESETZGEBUNG",
    body: "(1) Die konkurrierende Gesetzgebung erstreckt sich auf folgende Gebiete:\n1. das bürgerliche Recht, das Strafrecht, den gerichtlichen Aufbau, das Verfahren, die Rechtsanwaltsordnung, das Notarwesen und die Rechtsberatung,\n2. das Personenstandswesen, das Meldewesen und das Ausweiswesen,\n3. das Vereins- und Versammlungsrecht,\n4. die Aufenthalts- und Niederlassungsfreiheit,\n5. die Waffengesetzgebung und die Sprengstoffgesetzgebung.\n\n(2) Die konkurrierende Gesetzgebung umfasst weitere Bereiche, die in diesem Grundgesetz genannt sind.",
  },
  {
    id: 74,
    number: "Art. 75",
    title: "Konkurrierende Gesetzgebung — Rahmengesetzgebung (aufgehoben)",
    category: "GESETZGEBUNG",
    body: "Artikel 75 wird aufgehoben durch die Föderalismusreform I. Die frühere Rahmengesetzgebung wurde durch konkurrierende Gesetzgebung ersetzt.",
  },
  {
    id: 75,
    number: "Art. 76",
    title: "Einbringung von Gesetzesvorlagen",
    category: "GESETZGEBUNG",
    body: "(1) Gesetzesvorlagen werden beim Bundestage durch die Bundesregierung, aus der Mitte des Bundestages oder durch den Bundesrat eingebracht.\n\n(2) Vorlagen der Bundesregierung, die auf dem Gebiete der konkurrierenden Gesetzgebung liegen, sind nach der Beschließung durch die Bundesregierung zunächst dem Bundesrate zuzuleiten.\n\n(3) Der Bundesrat ist berechtigt, innerhalb von sechs Wochen zu diesen Vorlagen Stellung zu nehmen.\n\n(4) Gesetzesvorlagen aus der Mitte des Bundestages sind zunächst dem Bundesrat zuzuleiten. Der Bundestag kann binnen angemessener Frist über die Vorlage beschließen.",
  },
  {
    id: 76,
    number: "Art. 77",
    title: "Gesetzgebungsverfahren",
    category: "GESETZGEBUNG",
    body: "(1) Die Bundesgesetze werden vom Bundestage beschlossen. Sie werden nach ihrer Annahme durch den Präsidenten des Bundestages unverzüglich dem Bundesrate zuzuleiten.\n\n(2) Der Bundesrat kann verlangen, dass ein aus der Mitte des Bundesrates genanntes Gremium der Bundesregierung sowie Mitglieder des Bundestages an den Verhandlungen des Bundesrates zu den Gesetzesvorlagen teilnehmen.\n\n(3) Der Bundesrat kann binnen drei Wochen nach Eingang des Gesetzesbeschlusses Einspruch erheben.\n\n(4) Kommt ein Gesetz nicht zustande, so kann der Vermittlungsausschuss angerufen werden.",
  },
  {
    id: 77,
    number: "Art. 78",
    title: "Zustandekommen von Bundesgesetzen",
    category: "GESETZGEBUNG",
    body: "Ein vom Bundestage beschlossenes Gesetz kommt zustande, wenn der Bundesrat nicht Einspruch erhebt, der Vermittlungsausschuss nicht angerufen wird oder der Bundestag den Gesetzesbeschluss aufrechterhält.",
  },
  {
    id: 78,
    number: "Art. 79",
    title: "Änderung des Grundgesetzes",
    category: "VERFASSUNGSÄNDERUNG",
    body: "(1) Das Grundgesetz kann nur durch ein Gesetz geändert werden, das den Wortlaut des Grundgesetzes ausdrücklich ändert oder ergänzt.\n\n(2) Ein solches Gesetz bedarf der Zustimmung von zwei Dritteln der Mitglieder des Bundestages und zwei Dritteln der Stimmen des Bundesrates.\n\n(3) Eine Änderung dieses Grundgesetzes, durch welche die in den Artikeln 1 und 20 niedergelegten Grundsätze berührt werden, ist unzulässig. Eine Änderung der Vorschriften über die Mitwirkung der Länder bei der Gesetzgebung ist unzulässig.",
  },
  {
    id: 79,
    number: "Art. 80",
    title: "Erlass von Rechtsverordnungen",
    category: "GESETZGEBUNG",
    body: "(1) Durch Gesetz können die Bundesregierung, ein Bundesminister oder die Landesregierungen ermächtigt werden, Rechtsverordnungen zu erlassen.\n\n(2) Der Inhalt, der Zweck und der Umfang der erteilten Ermächtigung müssen im Gesetz bestimmt werden.\n\n(3) Die Ermächtigung kann zum Erlass von Rechtsverordnungen auch auf andere Stellen übertragen werden.\n\n(4) Der Bundesrat kann verlangen, dass der Bundesrat bei einem Rechtsverordnungsverfahren mitwirkt.",
  },
  {
    id: 80,
    number: "Art. 81",
    title: "Zustimmungsgesetzgebung",
    category: "GESETZGEBUNG",
    body: "(1) Ist im Falle des Artikels 68 der Bundestag aufgelöst, so kann der Bundesrat Gesetzesvorlagen der Bundesregierung als zustimmungspflichtig ansehen, wenn die Bundesregierung dringliche Maßnahmen als notwendig erklärt.\n\n(2) Der Bundesrat kann Gesetzesvorlagen als zustimmungspflichtig ansehen, wenn die Bundesregierung dringliche Maßnahmen als notwendig erklärt und der Bundesrat der Vorlage zustimmt.",
  },
  {
    id: 81,
    number: "Art. 82",
    title: "Ausfertigung und Verkündung von Gesetzen",
    category: "GESETZGEBUNG",
    body: "(1) Die nach den Vorschriften dieses Grundgesetzes zustande gekommenen Gesetze werden vom Bundespräsidenten nach Gegenzeichnung ausgefertigt und im Bundesgesetzblatte verkündet.\n\n(2) Bestimmt sich der Zeitpunkt des Inkrafttretens nicht aus dem Gesetze selbst, so tritt es mit dem vierzehnten Tage nach Ausgabe des Bundesgesetzblattes in Kraft.",
  },
  {
    id: 82,
    number: "Art. 83",
    title: "Ausführung von Bundesgesetzen",
    category: "VERWALTUNG",
    body: "Die Länder führen die Bundesgesetze als eigene Angelegenheit aus, soweit dieses Grundgesetz nichts anderes bestimmt oder zulässt.",
  },
  {
    id: 83,
    number: "Art. 84",
    title: "Landesverwaltung bei Bundesgesetzen",
    category: "VERWALTUNG",
    body: "(1) Führen die Länder Bundesgesetze als eigene Angelegenheit aus, so regeln sie die Einrichtung der Behörden und das Verwaltungsverfahren.\n\n(2) Der Bund kann durch Bundesgesetz allgemeine Verwaltungsvorschriften erlassen.\n\n(3) Der Bund kann beamtete Aufsichtsbehörden einrichten.\n\n(4) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 84,
    number: "Art. 85",
    title: "Bundesauftragsverwaltung",
    category: "VERWALTUNG",
    body: "(1) Führen die Länder Bundesgesetze im Auftrage des Bundes aus, so bleibt die Einrichtung der Behörden Sache der Länder.\n\n(2) Der Bund kann allgemeine Verwaltungsvorschriften erlassen.\n\n(3) Der Bund überwacht die Ausführung durch den Bundesrat.\n\n(4) Die Kosten, die durch die Ausführung von Bundesgesetzen entstehen, trägt der Bund.",
  },
  {
    id: 85,
    number: "Art. 87",
    title: "Bundesverwaltung",
    category: "VERWALTUNG",
    body: "(1) Es werden als bundesunmittelbare Körperschaften und Anstalten des öffentlichen Rechts verwaltet:\n1. die vom Bund betriebenen Postdienste und Telekommunikation,\n2. die Sozialversicherung und die Arbeitslosenversicherung.\n\n(2) Der Bund kann durch Gesetz für weitere Bereiche bundesunmittelbare Körperschaften und Anstalten errichten.",
  },
  {
    id: 86,
    number: "Art. 93",
    title: "Zuständigkeit des Bundesverfassungsgerichts",
    category: "BUNDESVERFASSUNGSGERICHT",
    body: "(1) Das Bundesverfassungsgericht entscheidet:\n1. über die Auslegung dieses Grundgesetzes aus Anlass von Streitigkeiten über den Umfang der Rechte und Pflichten eines obersten Bundesorgans,\n2. bei Meinungsverschiedenheiten oder Zweifeln über die förmliche und sachliche Vereinbarkeit von Bundesrecht oder Landesrecht mit diesem Grundgesetz,\n3. bei Meinungsverschiedenheiten über Rechte und Pflichten des Bundes und der Länder,\n4. in sonstigen öffentlich-rechtlichen Streitigkeiten zwischen dem Bund und den Ländern, zwischen verschiedenen Ländern oder zwischen einem Land und dem Bund.\n\n(2) Das Bundesverfassungsgericht entscheidet auch über Verfassungsbeschwerden.",
  },
  {
    id: 87,
    number: "Art. 94",
    title: "Zusammensetzung des Bundesverfassungsgerichts",
    category: "BUNDESVERFASSUNGSGERICHT",
    body: "(1) Das Bundesverfassungsgericht besteht aus Bundesrichtern und anderen Mitgliedern. Die Mitglieder des Bundesverfassungsgerichts werden je zur Hälfte vom Bundestage und vom Bundesrate gewählt.\n\n(2) Die Mitglieder des Bundesverfassungsgerichts dürfen weder dem Bundestage, dem Bundesrate, der Bundesregierung noch den entsprechenden Organen eines Landes angehören.\n\n(3) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 88,
    number: "Art. 95",
    title: "Oberste Bundesgerichte",
    category: "RECHTSPRECHUNG",
    body: "(1) Für die Bundesrepublik Deutschland wird ein Bundesgerichtshof, ein Bundesverwaltungsgericht, ein Bundesfinanzhof, ein Bundesarbeitsgericht und ein Bundessozialgericht errichtet.\n\n(2) Über die Zuständigkeit dieser Gerichte entscheidet ein Bundesgesetz.\n\n(3) Für die Wahrung der Einheitlichkeit der Rechtsprechung kann ein Gemeinsamer Senat der obersten Gerichtshöfe des Bundes errichtet werden.",
  },
  {
    id: 89,
    number: "Art. 96",
    title: "Bundesgerichte",
    category: "RECHTSPRECHUNG",
    body: "(1) Der Bund richtet für die sachliche Zuständigkeit der ordentlichen Gerichte ein Bundesgerichtshof, für die Verwaltungsgerichtsbarkeit ein Bundesverwaltungsgericht, für die Finanzgerichtsbarkeit einen Bundesfinanzhof, für die Arbeitsgerichtsbarkeit ein Bundesarbeitsgericht und für die Sozialgerichtsbarkeit ein Bundessozialgericht ein.\n\n(2) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 90,
    number: "Art. 97",
    title: "Unabhängigkeit der Richter",
    category: "RECHTSPRECHUNG",
    body: "(1) Die Richter sind unabhängig und nur dem Gesetze unterworfen.\n\n(2) Die hauptamtlich und planmäßig endgültig angestellten Richter können wider ihren Willen nur kraft richterlicher Entscheidung und nur aus Gründen und unter den Verfahren, die das Gesetz bestimmt, entlassen oder dauernd oder zeitweise ihres Amtes enthoben oder an eine andere Stelle oder in den Ruhestand versetzt werden.",
  },
  {
    id: 91,
    number: "Art. 98",
    title: "Richterliches Personalwesen",
    category: "RECHTSPRECHUNG",
    body: "(1) Die Rechtsstellung der Richter ist durch besonderes Gesetz zu regeln.\n\n(2) Der Bund kann für Bundesrichter ein einheitliches Richterrecht erlassen.\n\n(3) Die Länder können Richterwahlausschüsse einrichten.\n\n(4) Der Bund richtet einen Richterwahlausschuss ein.",
  },
  {
    id: 92,
    number: "Art. 99",
    title: "Landesverfassungsstreitigkeiten",
    category: "RECHTSPRECHUNG",
    body: "Streitigkeiten verfassungsrechtlicher Art innerhalb eines Landes können durch Landesgesetz dem Bundesverfassungsgericht zur Entscheidung zugewiesen werden.",
  },
  {
    id: 93,
    number: "Art. 100",
    title: "Richtervorlage bei Verfassungswidrigkeit",
    category: "RECHTSPRECHUNG",
    body: "(1) Hält ein Gericht ein Gesetz, auf dessen Gültigkeit es bei der Entscheidung ankommt, für verfassungswidrig, und ist sein Verfahren durch das Grundgesetz unmittelbar geregelt, so ist die Entscheidung dem Bundesverfassungsgericht vorzulegen.\n\n(2) Hält ein Gericht ein Gesetz, auf dessen Gültigkeit es bei der Entscheidung ankommt, für verfassungswidrig, und ist sein Verfahren nicht durch das Grundgesetz unmittelbar geregelt, so ist die Entscheidung dem zuständigen Landesverfassungsgericht vorzulegen.",
  },
  {
    id: 94,
    number: "Art. 101",
    title: "Ausnahmegerichtsbarkeit verboten",
    category: "RECHTSPRECHUNG",
    body: "(1) Ausnahmegerichte sind unzulässig. Niemand darf seinem gesetzlichen Richter entzogen werden.\n\n(2) Nur für bestimmte Fälle können Sondergerichte bestellt werden.",
  },
  {
    id: 95,
    number: "Art. 102",
    title: "Abschaffung der Todesstrafe",
    category: "RECHTSPRECHUNG",
    body: "Die Todesstrafe ist abgeschafft.",
  },
  {
    id: 96,
    number: "Art. 103",
    title: "Anspruch auf rechtliches Gehör",
    category: "RECHTSPRECHUNG",
    body: "(1) Vor Gericht hat jedermann Anspruch auf rechtliches Gehör.\n\n(2) Eine Tat kann nur bestraft werden, wenn die Strafbarkeit gesetzlich bestimmt war, bevor die Tat begangen wurde.\n\n(3) Niemand darf wegen derselben Tat auf Grund der allgemeinen Strafgesetze mehrmals bestraft werden.",
  },
  {
    id: 97,
    number: "Art. 104",
    title: "Garantie der persönlichen Freiheit bei Haft",
    category: "RECHTSPRECHUNG",
    body: "(1) Die Freiheit der Person kann nur auf Grund eines förmlichen Gesetzes und nur unter Beachtung der darin vorgeschriebenen Formen beschränkt werden.\n\n(2) Über die Zulässigkeit und Fortdauer einer Freiheitsentziehung hat nur der Richter zu entscheiden.\n\n(3) Personen, die nicht aufgrund eines richterlichen Haftbefehls festgenommen werden, müssen spätestens am Tage nach der Festnahme einem Richter vorgeführt werden.\n\n(4) Jede polizeiliche Haft darf die Dauer von zwei Tagen nicht überschreiten.",
  },
  {
    id: 98,
    number: "Art. 104a",
    title: "Finanzverantwortung",
    category: "FINANZWESEN",
    body: "(1) Bund und Länder tragen getrennt die Ausgaben, die sich aus der Wahrnehmung ihrer Aufgaben ergeben, wenn dieses Grundgesetz nichts anderes bestimmt.\n\n(2) Verwaltung der Bundesgesetze durch die Länder als eigene Angelegenheit: die Kosten trägt der Bund.\n\n(3) Verwaltung der Bundesgesetze durch die Länder im Auftrag: die Kosten trägt der Bund.",
  },
  {
    id: 99,
    number: "Art. 105",
    title: "Gesetzgebungskompetenz für Steuern",
    category: "FINANZWESEN",
    body: "(1) Der Bund hat die Befugnis zur Gesetzgebung über Zölle und Finanzmonopole.\n\n(2) Der Bund hat die konkurrierende Gesetzgebung über die übrigen Steuern.\n\n(3) Die Länder haben die Befugnis zur Gesetzgebung über die örtlichen Verbrauch- und Aufwandsteuern, solange und soweit der Bund von seiner Gesetzgebungskompetenz nicht Gebrauch macht.",
  },
  {
    id: 100,
    number: "Art. 106",
    title: "Verteilung der Steuereinnahmen",
    category: "FINANZWESEN",
    body: "(1) Die Erträge der Zölle und der Finanzmonopole stehen dem Bunde zu.\n\n(2) Die Erträge der übrigen Steuern stehen den Ländern zu, soweit dieses Grundgesetz nichts anderes bestimmt.\n\n(3) Die Erträge der Einkommensteuer und der Körperschaftsteuer stehen dem Bund und den Ländern gemeinsam zu.\n\n(4) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 101,
    number: "Art. 107",
    title: "Finanzausgleich",
    category: "FINANZWESEN",
    body: "Die Steuerforderungsrechte der Länder sind so zu begrenzen, dass ein angemessener Ausgleich zwischen den unterschiedlichen Finanzkraft der Länder erreicht wird.",
  },
  {
    id: 102,
    number: "Art. 108",
    title: "Finanzverwaltung",
    category: "FINANZWESEN",
    body: "(1) Zölle und Finanzmonopole werden durch Bundesfinanzbehörden verwaltet.\n\n(2) Die übrigen Steuern werden durch Landesfinanzbehörden verwaltet.\n\n(3) Das Nähere regelt ein Bundesgesetz, das der Zustimmung des Bundesrates bedarf.",
  },
  {
    id: 103,
    number: "Art. 109",
    title: "Haushaltswirtschaft von Bund und Ländern",
    category: "FINANZWESEN",
    body: "(1) Bund und Länder sind selbständig für ihre Haushaltswirtschaft verantwortlich.\n\n(2) Der Bund und die Länder haben bei ihrer Haushaltswirtschaft den Erfordernissen des gesamtwirtschaftlichen Gleichgewichts Rechnung zu tragen.\n\n(3) Die Bundesrepublik Deutschland und die Länder wirten im Rahmen ihrer Zuständigkeiten auf eine Stärkung des europäischen wirtschaftlichen und sozialen Zusammenhalts hin.",
  },
  {
    id: 104,
    number: "Art. 110",
    title: "Bundeshaushalt",
    category: "FINANZWESEN",
    body: "(1) Alle Einnahmen und Ausgaben des Bundes sind in den Haushaltsplan einzustellen; bei der Bundesbank und bei zweckbestimmten Einnahmen ist übersteigender Ertrag in den Haushaltsplan einzustellen.\n\n(2) Der Haushaltsplan ist in Einnahmen und Ausgaben auszugleichen.\n\n(3) Der Haushaltsplan wird für ein oder mehrere Jahre, nach Jahren getrennt, aufgestellt.",
  },
  {
    id: 105,
    number: "Art. 111",
    title: "Vorläufige Haushaltsführung",
    category: "FINANZWESEN",
    body: "(1) Ist bis zum Schluss eines Rechnungsjahres der Bundeshaushalt für das folgende Jahr nicht durch Gesetz festgestellt, so ist bis zu dessen Inkrafttreten der Bundesminister der Finanzen ermächtigt, alle Ausgaben zu leisten, die notwendig sind, um die bestehenden Einrichtungen zu erhalten.\n\n(2) Der Bundesminister der Finanzen ist ermächtigt, die erforderlichen Mittel zu beschaffen.",
  },
  {
    id: 106,
    number: "Art. 112",
    title: "Überplanmäßige und außerplanmäßige Ausgaben",
    category: "FINANZWESEN",
    body: "Ausgaben, die den im Haushaltsplan angesetzten Betrag übersteigen, sowie Ausgaben, die nicht im Haushaltsplan vorgesehen sind, bedürfen der Zustimmung des Bundesministers der Finanzen. Diese Zustimmung darf nur im Falle eines unvorhergesehenen und unabweisbaren Bedürfnisses erteilt werden.",
  },
  {
    id: 107,
    number: "Art. 113",
    title: "Einsparungen und Überschüsse",
    category: "FINANZWESEN",
    body: "Der Bundestag kann Einsparungen im Bundeshaushaltsplan nur beschließen, wenn die Bundesregierung der Einsparung zustimmt.",
  },
  {
    id: 108,
    number: "Art. 114",
    title: "Rechnungslegung",
    category: "FINANZWESEN",
    body: "(1) Der Bundesminister der Finanzen legt dem Bundestage und dem Bundesrate über alle Einnahmen und Ausgaben sowie über das Vermögen und die Schulden des Bundes Rechnung.\n\n(2) Der Bundesrechnungshof, dessen Mitglieder richterliche Unabhängigkeit haben, prüft die Rechnung sowie die Wirtschaftlichkeit und Ordnungsmäßigkeit der Haushalts- und Wirtschaftsführung.",
  },
  {
    id: 109,
    number: "Art. 115",
    title: "Kreditaufnahme",
    category: "FINANZWESEN",
    body: "(1) Die Aufnahme von Krediten sowie die Übernahme von Bürgschaften, Garantien oder sonstigen Gewährleistungen, die zu Ausgaben in künftigen Rechnungsjahren führen können, bedürfen einer der Höhe nach bestimmten oder bestimmbaren Ermächtigung durch Bundesgesetz.\n\n(2) Die Einnahmen aus Krediten dürfen den im Haushaltsplan veranschlagten Betrag für Investitionen nicht überschreiten. Ausnahmen sind nur zulässig zur Abwehr einer Störung des gesamtwirtschaftlichen Gleichgewichts.",
  },
  {
    id: 110,
    number: "Art. 115a",
    title: "Feststellung des Verteidigungsfalls",
    category: "VERTEIDIGUNG",
    body: "(1) Der Bundestag stellt mit Zustimmung des Bundesrates den Verteidigungsfall fest, wenn der Bund das Gebiet der Bundesrepublik Deutschland mit Waffengewalt angreift oder ein solcher Angriff unmittelbar droht.\n\n(2) Die Feststellung erfolgt auf Antrag der Bundesregierung und bedarf der Zustimmung des Bundestages und des Bundesrates.\n\n(3) Die Feststellung wird vom Bundespräsidenten im Bundesgesetzblatt verkündet.",
  },
  {
    id: 111,
    number: "Art. 115b",
    title: "Befehlsgewalt im Verteidigungsfall",
    category: "VERTEIDIGUNG",
    body: "Mit der Verkündung, dass der Verteidigungsfall eingetreten ist, geht die Befehls- und Kommandogewalt über die Streitkräfte auf den Bundeskanzler über.",
  },
  {
    id: 112,
    number: "Art. 115c",
    title: "Gesetzgebung im Verteidigungsfall",
    category: "VERTEIDIGUNG",
    body: "(1) Im Verteidigungsfall hat der Bund die konkurrierende Gesetzgebungsbefugnis auch auf die Gesetzgebung der Länder. Die Gesetze des Bundes können mit Zustimmung des Bundesrates auch zur Ausführung von Bundesgesetzen dienen.\n\n(2) Der Bundesrat kann in Angelegenheiten, die in den Bereich der Gesetzgebung des Bundes fallen, durch Gesetze die Bundesregierung ermächtigen.\n\n(3) Gesetze zur Abwehr eines drohenden oder bestehenden Gefahrenzustandes bedürfen der Zustimmung des Bundesrates.",
  },
  {
    id: 113,
    number: "Art. 115d",
    title: "Wahlperiode im Verteidigungsfall",
    category: "VERTEIDIGUNG",
    body: "(1) Eine Auflösung des Bundestages ist während des Verteidigungsfalls nicht zulässig.\n\n(2) Die Wahlperiode des Bundestages endet sechs Monate nach Beendigung des Verteidigungsfalls.\n\n(3) Die Wahlperiode des Bundestages kann durch Bundesgesetz, das der Zustimmung des Bundesrates bedarf, verlängert werden.",
  },
  {
    id: 114,
    number: "Art. 115e",
    title: "Verteidigungsrat",
    category: "VERTEIDIGUNG",
    body: "(1) Ist der Bundestag im Verteidigungsfall nicht handlungsfähig, so nimmt ein gemeinsamer Ausschuss aus dem Bundestage und dem Bundesrate die Rechte des Bundestages wahr.\n\n(2) Der gemeinsame Ausschuss besteht aus Mitgliedern des Bundestages und Mitgliedern des Bundesrates.\n\n(3) Der gemeinsame Ausschuss nimmt die Rechte des Bundestages und des Bundesrates wahr.",
  },
  {
    id: 115,
    number: "Art. 115l",
    title: "Beendigung des Verteidigungsfalls",
    category: "VERTEIDIGUNG",
    body: "(1) Der Verteidigungsfall ist zu beenden, wenn der Bundestag mit Zustimmung des Bundesrates feststellt, dass der Angriff abgewehrt ist oder nicht mehr droht.\n\n(2) Maßnahmen, die aufgrund des Verteidigungsfalls getroffen wurden, sind aufzuheben.\n\n(3) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 116,
    number: "Art. 120",
    title: "Kriegsfolgelasten",
    category: "FINANZWESEN",
    body: "(1) Der Bund trägt die Aufwendungen für die durch den Krieg verursachten Lasten.\n\n(2) Der Bund und die Länder können gemeinsame Ausgaben nach Maßgabe eines Bundesgesetzes tragen.",
  },
  {
    id: 117,
    number: "Art. 121",
    title: "Besetzung des Bundesverfassungsgerichts",
    category: "BUNDESVERFASSUNGSGERICHT",
    body: "Das Bundesverfassungsgericht besteht aus Bundesrichtern und anderen Mitgliedern. Die Mitglieder des Bundesverfassungsgerichts werden je zur Hälfte vom Bundestage und vom Bundesrate gewählt. Sie dürfen weder dem Bundestage, dem Bundesrate, der Bundesregierung noch den entsprechenden Organen eines Landes angehören.",
  },
  {
    id: 118,
    number: "Art. 122",
    title: "Übergangsregelungen",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Vor der Konstituierung der Volksvertretungen in den Ländern und vor der Bildung der Bundesregierung können die Länder ihre eigenen Verfassungen geben.\n\n(2) Die landesrechtlichen Vorschriften können bis zur anderweitigen Regelung durch die Länder beibehalten werden.",
  },
  {
    id: 119,
    number: "Art. 123",
    title: "Fortgeltung von Recht",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Recht aus der Zeit vor dem Inkrafttreten des Grundgesetzes gilt fort, soweit es nicht im Widerspruch zum Grundgesetz steht.\n\n(2) Die nach dem 8. Mai 1945 erlassenen Rechtsvorschriften der alliierten Militärregierungen bleiben unberührt.",
  },
  {
    id: 120,
    number: "Art. 124",
    title: "Überleitung der Gesetzgebung",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Recht, das nach den Bestimmungen des Grundgesetzes als Bundesrecht fortgilt, kann durch Bundesgesetz geändert werden.",
  },
  {
    id: 121,
    number: "Art. 125",
    title: "Fortgeltung von Bundesrecht als Landesrecht",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Recht, das als Bundesrecht erlassen wurde und nach den Bestimmungen des Grundgesetzes als Landesrecht fortgilt, kann durch Landesgesetz geändert werden.",
  },
  {
    id: 122,
    number: "Art. 125a",
    title: "Fortgeltung von Bundesrecht",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Recht, das als Bundesrecht erlassen wurde und nach den Bestimmungen des Grundgesetzes als Landesrecht fortgilt, gilt als Bundesrecht fort, soweit es nach dem Inkrafttreten des Grundgesetzes in dem betreffenden Bereich der Gesetzgebung nicht ausdrücklich geändert worden ist.\n\n(2) Recht, das vor dem Inkrafttreten des Grundgesetzes erlassen wurde und als Bundesrecht fortgilt, kann durch Bundesgesetz geändert werden.",
  },
  {
    id: 123,
    number: "Art. 126",
    title: "Strafrechtliche Bestimmungen",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Soweit in dem nach dem 8. Mai 1945 erlassenen Recht Strafen angedroht werden, ist es aufzuheben, soweit es nicht ausdrücklich aufrechterhalten wird.",
  },
  {
    id: 124,
    number: "Art. 127",
    title: "Wirtschaftsrat für das vereinigte Wirtschaftsgebiet",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Der Wirtschaftsrat des Vereinigten Wirtschaftsgebietes kann mit der Mehrheit seiner Stimmen die Auflösung des Vereinten Wirtschaftsgebietes beschließen.",
  },
  {
    id: 125,
    number: "Art. 128",
    title: "Fortgeltung von Beamtenverhältnissen",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Die beamtenrechtlichen Vorschriften, die vor dem Inkrafttreten des Grundgesetzes erlassen wurden, gelten fort, soweit sie nicht im Widerspruch zum Grundgesetz stehen.",
  },
  {
    id: 126,
    number: "Art. 129",
    title: "Fortgeltung von Rechtsvorschriften",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Rechtsvorschriften, die vor dem Inkrafttreten des Grundgesetzes erlassen wurden, gelten fort, soweit sie nicht im Widerspruch zum Grundgesetz stehen.\n\n(2) Die Vorschriften können durch die zuständigen Organe geändert oder aufgehoben werden.",
  },
  {
    id: 127,
    number: "Art. 130",
    title: "Überleitung von Behörden",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Die Verwaltung des Bundes und der Länder wird in Übereinstimmung mit den Bestimmungen des Grundgesetzes geregelt.\n\n(2) Die Behörden, die vor dem Inkrafttreten des Grundgesetzes errichtet wurden, können bis zur anderweitigen Regelung bestehen bleiben.",
  },
  {
    id: 128,
    number: "Art. 131",
    title: "Versorgungsansprüche",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Die Versorgungsansprüche der Personen, die vor dem Inkrafttreten des Grundgesetzes in einem öffentlichen Dienstverhältnis standen, sind zu regeln.",
  },
  {
    id: 129,
    number: "Art. 132",
    title: "Amtsverhältnisse",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Personen, die vor dem Inkrafttreten des Grundgesetzes in einem öffentlichen Dienstverhältnis standen, können in ihrem Amt belassen werden.\n\n(2) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 130,
    number: "Art. 133",
    title: "Eigentumsverhältnisse der Länder",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Das Vermögen des Reiches wird auf dem Wege der Bundesgesetzgebung geregelt.",
  },
  {
    id: 131,
    number: "Art. 134",
    title: "Reichsvermögen",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Das Reichsvermögen geht, soweit es nicht nach Artikeln 89 und 90 this Grundgesetzes dem Bund zusteht, auf die Länder über.\n\n(2) Der Bund kann das Reichsvermögen für Zwecke der Bundesverwaltung behalten.",
  },
  {
    id: 132,
    number: "Art. 135",
    title: "Vermögen von Gebietskörperschaften",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Das Vermögen der Gebietskörperschaften, die durch die Neugliederung des Bundesgebietes aufgehoben werden, geht auf die Gebietskörperschaften über, die an ihre Stelle treten.\n\n(2) Das Nähere regelt ein Bundesgesetz.",
  },
  {
    id: 133,
    number: "Art. 135a",
    title: "Schulden der ehemaligen Gebietskörperschaften",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Das Nähere über die Schulden der Gebietskörperschaften, die aufgehoben werden, wird durch Bundesgesetz geregelt.",
  },
  {
    id: 134,
    number: "Art. 136",
    title: "Volksgesetzgebung auf Bundesebene",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Die during der Übergangszeit auf Landesebene erlassenen Bestimmungen bleiben unberührt.\n\n(2) Über die Einführung von Volksentscheiden auf Bundesebene kann durch Bundesgesetz entschieden werden.",
  },
  {
    id: 135,
    number: "Art. 137",
    title: "Religionsgemeinschaften",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Die Bestimmungen des Artikels 141 bleiben unberührt.\n\n(2) Es besteht keine Staatskirche.\n\n(3) Die Gewährleistung der ungestörten Religionsausübung bleibt dem Grundgesetz überlassen.\n\n(4) Das Recht, Kirchensteuern zu erheben, wird gewährleistet.\n\n(5) Die religionsgemeinschaftlichen Vereinigungen, die Körperschaften des öffentlichen Rechts sind, behalten ihre Eigenschaft.",
  },
  {
    id: 136,
    number: "Art. 138",
    title: "Anstaltsbeziehungen",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Die auf Gesetz, Vertrag oder besonderen Rechtstiteln beruhenden Leistungen an die Religionsgemeinschaften werden durch Landesgesetz geregelt.",
  },
  {
    id: 137,
    number: "Art. 139",
    title: "Entnazifizierung",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Die zur „Befreiung des deutschen Volkes vom Nationalsozialismus und Militarismus\" erlassenen Bestimmungen werden von den Bestimmungen des Grundgesetzes nicht berührt.",
  },
  {
    id: 138,
    number: "Art. 140",
    title: "Schulgebete",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Die Bestimmungen des Artikels 141 des Grundgesetzes in der Fassung vom 11. August 1919 bleiben in Kraft, soweit sie nicht dem Grundgesetz widersprechen.",
  },
  {
    id: 139,
    number: "Art. 141",
    title: "Religiöse Bedürfnisse",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Soweit das Bedürfnis nach Gottesdienst und Seelsorge im Heer, in Krankenhäusern, Strafanstalten oder sonstigen öffentlichen Anstalten besteht, sind die Religionsgemeinschaften zur Vornahme der gottesdienstlichen Handlungen zuzulassen.",
  },
  {
    id: 140,
    number: "Art. 142",
    title: "Landesverfassungsrechtliche Garantien",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Unbeschadet der in Artikel 53 der Verfassung des Deutschen Reiches vom 11. August 1919 niedergelegten Vorschriften werden durch die in den Landesverfassungen enthaltenen weitergehenden Grundrechtsbestimmungen die in diesem Grundgesetz verbürgten Grundrechte nicht beschränkt.",
  },
  {
    id: 141,
    number: "Art. 143",
    title: "Abweichungen in den neuen Ländern",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "(1) Recht, das dem Bund und den Ländern in den Gebieten, die am 3. Oktober 1990 der Bundesrepublik Deutschland beigetreten sind, durch die Entwikelung in den Bereichen der Artikel 1 bis 19 des Grundgesetzes entstanden ist, kann bis zum 31. Dezember 1992 von den in diesem Grundgesetz niedergelegten Bestimmungen abweichen.\n\n(2) Abweichungen, die über den 31. Dezember 1992 hinausgehen, bedürfen der Zustimmung von zwei Dritteln der Mitglieder des Bundestages und zwei Dritteln der Stimmen des Bundesrates.",
  },
  {
    id: 142,
    number: "Art. 143a",
    title: "Überleitung von Bundesvermögen",
    category: "ÜBERGANGSBESTIMMUNGEN",
    body: "Die Regelung des Übergangs von Vermögen der bisherigen DDR auf den Bund und die Länder erfolgt durch Bundesgesetz.",
  },
  {
    id: 143,
    number: "Art. 144",
    title: "Inkrafttreten des Grundgesetzes",
    category: "SCHLUSSBESTIMMUNGEN",
    body: "(1) Das Grundgesetz bedarf in den ersten drei Jahren seiner Geltungsdauer der Zustimmung der Militärgouverneure der westlichen Besatzungsmächte.\n\n(2) Die Militärgouverneure können die Geltungsdauer des Grundgesetzes verlängern.\n\n(3) Das Grundgesetz tritt nach der Genehmigung durch die Militärgouverneure in Kraft.",
  },
  {
    id: 144,
    number: "Art. 145",
    title: "Verkündung des Grundgesetzes",
    category: "SCHLUSSBESTIMMUNGEN",
    body: "(1) Der Parlamentarische Rat verkündet das Grundgesetz im Bundesgesetzblatt und setzt den Zeitpunkt seines Inkrafttretens fest.\n\n(2) Das Grundgesetz tritt mit Ablauf des Tages der Verkündung in Kraft.",
  },
  {
    id: 145,
    number: "Art. 146",
    title: "Geltungsdauer des Grundgesetzes",
    category: "SCHLUSSBESTIMMUNGEN",
    body: "Dieses Grundgesetz, das nach Vollendung der Einheit und Freiheit Deutschlands für das gesamte deutsche Volk gilt, verliert seine Gültigkeit an dem Tage, an dem eine Verfassung in Kraft tritt, die von dem deutschen Volke in freier Entscheidung beschlossen worden ist.",
  },
];
